### PR TITLE
Sell order

### PR DESCRIPTION
**Pull request by koraycaglar**
- Sell function added.
- The bot sells %99.5 of the coins it bought in order to avoid exceptions
- "coins_in_hand" dictionary stores the amount of coins the bot bought and currently holding.
- nltk.download('vader_lexicon') added

- Selling on BCH/USDT pairing gives this exception for some reason (I can't tell why):
BinanceAPIException: APIError(code=-1121): Invalid symbol.
- When buying/selling this exception sometimes happens:
BinanceAPIException: APIError(code=-1013): Filter failure: LOT_SIZE

Feel free to change/copy anything you see fit.

### CODE REVIEW

**Review by CyberPunkMetalHead — COMMENTED** [review]
Hi, thank you for your commit! Someone has just contributed to making the requests Async, and the script is much faster now. I won't be able to commit your pull request so it doesn't override the changes, but I will manually add your changes in the code and push a commit :)

**Comment by koraycaglar** [comment]
That's fine! Have a great day :)

**Comment by CyberPunkMetalHead** [comment]
You too! Your contribution and the latest version of the code now lives in a new branch at: https://github.com/CyberPunkMetalHead/Binance-News-Sentiment-Bot/tree/Binance-News-Sentiment-Bot-Plus-Sell

During my testing it seems that the loop inside the buy function doesn't iterate through all the coins in keywords. I'm looking into it, but if you're still interested to contribute, it would be great if you can help out with that :)

**Comment by koraycaglar** [comment]
Yeah I just saw it on Issues and answered it. Let me know how it turns out :)

**Comment by CyberPunkMetalHead** [comment]
Amazing, thank you :)

**Pull request closed without merging**
